version: "3.9"
services:
  node1:
    build:
      context: ./node
      dockerfile: Dockerfile
    image: blockswap/node:dev
    container_name: blockswap-node1
    ports:
      - "30333:30333"
      - "9933:9933"
      - "9944:9944"
    command: ["/usr/local/bin/blockswap-node"]
    volumes:
      - node1_data:/data
  node2:
    image: blockswap/node:dev
    container_name: blockswap-node2
    ports:
      - "30334:30333"
      - "9934:9933"
      - "9945:9944"
    depends_on: [node1]
    command: ["/usr/local/bin/blockswap-node"]
    volumes:
      - node2_data:/data
volumes:
  node1_data: {}
  node2_data: {}
