name: Export Mermaid Diagrams

on:
  workflow_dispatch: {}
  push:
    paths:
      - 'docs/diagrams/*.mmd'
      - 'scripts/export-diagrams.sh'

jobs:
  export:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Chromium dependencies (for Puppeteer)
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            ca-certificates fonts-liberation \
            libasound2 libatk-bridge2.0-0 libatk1.0-0 \
            libcups2 libdbus-1-3 libgdk-pixbuf2.0-0 \
            libnspr4 libnss3 libx11-xcb1 libxcomposite1 \
            libxdamage1 libxrandr2 libgbm1 libxss1 xdg-utils \
            libpangocairo-1.0-0 libpango-1.0-0 libdrm2 libgtk-3-0

      - name: Install mermaid-cli
        run: npm install -g @mermaid-js/mermaid-cli@9

      - name: Render diagrams
        run: |
          chmod +x scripts/export-diagrams.sh
          ./scripts/export-diagrams.sh

      - name: Commit and push generated images
        uses: EndBug/add-and-commit@v9
        with:
          author_name: 'blockswap-bot'
          author_email: 'noreply@blockswap'
          message: 'chore: export diagrams (generated PNGs)'
          add: 'docs/diagrams/*.png'
